# Generated by Django 5.2.8 on 2025-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0002_healthconnectusers_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthconnectusers',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
