# Generated by Django 5.2.8 on 2026-01-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0003_alter_healthconnectusers_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconnectusers',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='healthconnectusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
